version: 1.2
workflows:
   - subclass: cwl
     primaryDescriptorPath: /dockstore.cwl
     testParameterFiles:
     - /test/dockstore.cwl.json
     name: md5sum
   - subclass: cwl
     primaryDescriptorPath: /dockstore.cwl
     testParameterFiles:
     - /test/dockstore.cwl.json
     name: foobar
