version: 1.2
workflows:
   - subclass: wdl
     primaryDescriptorPath: /Dockstore.wdl
     name: md5sum
   - subclass: cwl
     primaryDescriptorPath: /dockstore.cwl
     testParameterFiles:
     - /test/dockstore.cwl.json
     name: foobar
     authors:
     - name: Charles Overbeck
       email: notreal@fake.com
