version: 1.2
workflows:
   - subclass: cwl
     primaryDescriptorPath: /dockstore.cwl
     testParameterFiles:
     - /test/dockstore.cwl.json
     name: md5sum
     authors:
     - orcid: 0000-0001-7641-7724
   - subclass: cwl
     primaryDescriptorPath: /dockstore.cwl
     testParameterFiles:
     - /test/dockstore.cwl.json
     name: Foobar
     authors:
     - name: Charles Overbeck
       email: notreal@fake.com
   - subclass: cwl
     primaryDescriptorPath: /dockstore.cwl
     testParameterFiles:
     - /test/dockstore.cwl.json
     name: blah
     authors:
     - name: Charles Overbeck
       email: notreal@fake.com
