version: 1.2
workflows:
   - subclass: cwl
     primaryDescriptorPath: /dockstore.cwl
     testParameterFiles:
     - /test/dockstore.cwl.json
     name: md5sum
   - subclass: cwl
     primaryDescriptorPath: /dockstore.cwl
     testParameterFiles:
     - /test/dockstore.cwl.json
     name: foobar
services:
  - subclass: DOCKER_COMPOSE
    name: UCSC Xena Browser
    author: UCSC Genomics Institute
    description: |
      The UCSC Xena browser is an exploration tool for public and private,
      multi-omic and clinical/phenotype data.
      It is recommended that you configure a reverse proxy to handle HTTPS
    files:
       - xenahub/docker-compose.yml
       - xenahub/README.md
       - xenahub/stand_up.sh
       - xenahub/load.sh
       - xenahub/port.sh
       - xenahub/stop.sh
       - xenahub/xena-all.json

    scripts:
      start: stand_up.sh
      postprovision: load.sh
      port: port.sh
      stop: stop.sh

    environment:
      httpPort:
          default: 7222
          description: The host's HTTP port. The default is 7222.

    data:
      dataset_1:
          targetDirectory: xena/files 
          files:
              tsv:
                  description: Data for Xena in TSV format
              metadata:
                  description: The metadata, in JSON format, that corresponds to the previous tsv file
